Вопросы по моделям!
DerSerhii/Module-e-shop pull request #1
Opened 2022-06-22 10:09 UTC by DerSerhii

1. В нашем чудо-магазине)) цены пока будут фиксированы? Покупка хранит экземпляр товара, пока будут возвращать, он может изменится. Или делать атрибут в Покупке и хранить цену на момент продажи? 
2. Возврат будет всего товара купленного за один раз или можно возвращать 1 ручку из 3, к примеру? (лучше все, нечего перебирать)))

2022-06-22 10:22 UTC, PonomaryovVladyslav commented
1) ну раз ты спросил, то храни, раньше всем пофигу было)
2) только целиком

2022-06-29 19:23 UTC, DerSerhii commented
На всякий случай, оповещу и сообщением)

2022-06-30 16:17 UTC, PonomaryovVladyslav requested changes
Странные ощущения, с одной стороны вроде всё должно работать, с другой просто гора избыточного\массивного кода, который можно было бы заметно упростить. Если ты писал это сам, то в целом молодец, но на диплом подумай для каждого решения можно сделать легче, или я на приёме задрочу глупыми вопросами, а почему тут именно так, а не по другому :)

Сделай по людски ретурн в гет контексте и заапрувлю, а то эта конструкция заставляет мой глаз дёргаться

2022-06-30 16:17 UTC, PonomaryovVladyslav commented on e_shop/views.py
> +        return dict(list(context.items()) + list(context_add.items()))
Зачем такая страшная конструкция?)) чем тебе обычный апдейт не угодил?)

2022-06-30 16:17 UTC, PonomaryovVladyslav commented on e_shop/views.py
> +        return dict(list(context.items()) + list(context_add.items()))
Ну и тут само собой тоже и если в других места увижу, то тоже, дальше писать не буду

2022-06-30 16:17 UTC, PonomaryovVladyslav commented on e_shop/views.py
> +            self.request.session["msg_lack_money"] = f"{purchase_total - wallet_customer}"
В принципе ок, но почему не встроенные мессаджес, вроде ж проще и удобнее. Это не ошибка, просто на глаза попалось

2022-06-30 16:17 UTC, PonomaryovVladyslav commented on e_shop/views.py
> +            context.update({"msg_request_refund": msg_request_refund})
Ага, тоесть ты всё таки знаешь про метод апдейт))

2022-06-30 16:17 UTC, PonomaryovVladyslav commented on e_shop/views.py
> +    def refusal_refund(self):
Если у тебя всё отличие в тексте сообщения и одном сообщении и одном вызове менеджера зачем тут два метода? Опять же оно не ошибка, но всё смотрится слишком массивно и избыточно

2022-06-30 16:17 UTC, PonomaryovVladyslav commented on e_shop/views.py
> +        wallet_form.save()
не атомарненько)

2022-06-30 17:43 UTC, DerSerhii commented
Как сделать легче подумаю, но уже свежим взглядом, через пару-тройку дней, а то взгляд замылен, мне кажется венцом творенья))

2022-06-30 17:59 UTC, PonomaryovVladyslav approved these changes

2022-06-30 18:10 UTC, merged